service: blog
image: karim848/blog

# Añade los servidores a los que vas a desplegar.
servers:
  web:
    hosts:
      - 192.168.0.29 # La IP de tu VM Debian

registry:
  username: karim848
  password:
    - KAMAL_REGISTRY_PASSWORD

# Volúmenes para que los datos no se borren.
volumes:
  - "storage:/rails/storage"

# Corregimos el usuario SSH
ssh:
  user: user1 # El usuario que creaste en Debian

builder:
  arch: amd64